#!/bin/bash
# Dark Factory Plugin — Alerting System
# Sends alerts via macOS notification, GitHub issue, or log
#
# Usage: ./alert.sh <level> <title> <message>
# Levels: info, warning, critical

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source config loader
source "$PLUGIN_ROOT/lib/config.sh"
load_project_config

ALERT_LOG="$DF_FACTORY_DIR/alerts.log"

LEVEL="${1:?Usage: alert.sh <level> <title> <message>}"
TITLE="${2:?Missing title}"
MESSAGE="${3:?Missing message}"
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- Log alert ---
echo "[$TIMESTAMP] [$LEVEL] $TITLE: $MESSAGE" >> "$ALERT_LOG"

# --- macOS Notification ---
if command -v osascript &>/dev/null; then
  # Escape strings for AppleScript (backslashes then double quotes)
  _as_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
  safe_msg=$(_as_escape "$MESSAGE")
  safe_title=$(_as_escape "$TITLE")
  safe_project=$(_as_escape "$DF_PROJECT_NAME")

  case "$LEVEL" in
    critical)
      osascript -e "display notification \"$safe_msg\" with title \"$safe_project Dark Factory CRITICAL\" subtitle \"$safe_title\" sound name \"Sosumi\""
      ;;
    warning)
      osascript -e "display notification \"$safe_msg\" with title \"$safe_project Dark Factory Warning\" subtitle \"$safe_title\""
      ;;
    info)
      osascript -e "display notification \"$safe_msg\" with title \"$safe_project Dark Factory\" subtitle \"$safe_title\""
      ;;
  esac
fi

# --- GitHub Issue (critical alerts only) ---
if [ "$LEVEL" = "critical" ] && [ -n "$DF_GITHUB_REPO" ] && command -v gh &>/dev/null; then
  if [ "${DARK_FACTORY_GH_ALERTS:-false}" = "true" ]; then
    gh issue create -R "$DF_GITHUB_REPO" \
      --title "[Dark Factory Alert] $TITLE" \
      --body "## $LEVEL Alert

**Time**: $TIMESTAMP
**Project**: $DF_PROJECT_NAME
**Title**: $TITLE
**Message**: $MESSAGE

---
Generated by Dark Factory alerting system." \
      --label "dark-factory,alert,$LEVEL" \
      2>/dev/null || echo "Failed to create GitHub issue"
  fi
fi

# --- Console output ---
case "$LEVEL" in
  critical) echo "CRITICAL: $TITLE — $MESSAGE" ;;
  warning)  echo "WARNING: $TITLE — $MESSAGE" ;;
  info)     echo "INFO: $TITLE — $MESSAGE" ;;
esac
